### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by gdbtheboss** [asagarwal/rest-api-with-java#2]
When I try to run this again test.salesforce.com with valid credentials, I am getting javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure. Will this not work if the URL is https?

**Comment by gdbtheboss** [comment]
I figured it out the problem. It is the java version, used 1.8 and now it is working.

**Comment by asagarwal** [comment]
Great. Cheers!
